name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '18 4 * * 3'

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@d0b50195d14745b9a9a8a41cf3bb7ecd874af37a # V0.1.1
    secrets: inherit
